# Generated by Django 4.1.7 on 2023-03-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_blogobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogobj',
            name='short_desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
